name: Automated Commits
on: 
  push:
    branches: [ main ]
      paths:
      - 'source/sphinx/recipes/**'

  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  release-recipes:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: |
      (
        (contains(github.event.head_commit.message, 'edited') || contains(github.event.head_commit.message, 'created'))
        && !contains(github.event.head_commit.message, 'testing')
      )
      || github.event_name == 'workflow_dispatch'
    steps:
      - name: Set tag_name
        id: set_tag_name
        run: echo "::set-output name=tag_name::v$(date +'%m-%d-%Y-%H%M')"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create zip archive
        run: |
          zip -j Recipes.zip source/sphinx/recipes/*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: All_Recipes
          path: Recipes.zip
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: All_Recipes
      - name: Release Recipes
        uses: softprops/action-gh-release@v1
        with:
          files: Recipes.zip
          name: Recipes
          tag_name: ${{ steps.set_tag_name.outputs.tag_name }}
      
  setup:
    if: |
      (contains(github.event.head_commit.message, 'edited') ||
      contains(github.event.head_commit.message, 'created')) || 
      contains(github.event.head_commit.message, 'build') ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - uses: actions/setup-python@v4
      with:
          python-version: '3'
          cache: 'pip'

    - name: Add automated submission to changelog
      if: "contains(github.event.head_commit.message, 'edited') || contains(github.event.head_commit.message, 'created')" #If we are manually building, skip the changelog steps
      run: sed -i "4i- ${{ github.event.head_commit.message }}" source/sphinx/builds.rst

    - name: Add last build date to index
      run: |
        export TZ="America/Chicago"
        sed -i '$c\'"Last built at $(date +'%l:%M:%S %p on %-m-%-d-%Y.')" source/sphinx/index.rst

    - name: Commit automated changes
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: "Automated updates"
        add: "['source/sphinx/builds.rst','source/sphinx/index.rst']"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
