name: Build and Deploy
on:
  workflow_run:
    workflows: [Automated Commits]
    types: [completed]
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    # if: contains(github.event.head_commit.message, 'Automated updates')
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with: 
        documentation_path: ./source/sphinx
        requirements_path: ./source/sphinx/requirements.txt

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
    
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
