name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: BlakeDarrow
  GITHUB_REPOSITORY: BlakeDarrow/DarrowTools
  GITHUB_TOKEN: ${{ secrets.CREATE_SITE_SECRET }}

on: 
  push:
    branches: [ main ]



jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_SITE_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
  
      - name: Sphinx Pages 
        # You may pin to the exact commit or the version.
        # uses: seanzhengw/sphinx-pages@70dd0557fc226cfcd41c617aec5e9ee4fce4afe2
        uses: seanzhengw/sphinx-pages@v1
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: secrets.GITHUB_TOKEN
          # Auto create a README.md file at branch gh-pages root with repo/branch/commit links
        
        
